server:
  port: 9090
  



spring:
  datasource:
    url: ${cloud.services.ams-ui.connection.jdbcUrl:jdbc:mysql://localhost:3306/attendence_ms?useSSL=false&user=root&password=root}


  data:
    mongodb:
      database: Attendance
      host: localhost
      port: 27017

  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQLDialect
    show-sql: true
    
  application:
    name: employee



    
    
zuul:
  routes:
    employee.path : /manager
    employee.service_id : manager
    
    getApprovalList.path : /getApprovalList
    getApprovalList.service-id :manager
    
    ams.path : /js/ams1.js
    ams.service-id : manager
    
    getPendingList.path : /getPendingList
    getPendingList.service-id : manager
    
    Approved.path : /Approved
    Approved.service-id : manager
    


   
