  
spring:
  datasource:
    url: ${cloud.services.ams-ui.connection.jdbcUrl:jdbc:mysql://localhost:3306/attendence_ms?useSSL=false&user=root&password=root}
  application:
    name: employee


  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQLDialect
    show-sql: true
    

zuul:
  routes:
    employee.path : /manager
    employee.service_id : Manager
    
    getApprovalList.path : /getApprovalList
    getApprovalList.service-id : Manager
    
    ams.path : /js/ams1.js
    ams.service-id : Manager
    
    getPendingList.path : /getPendingList
    getPendingList.service-id : Manager
    
    Approved.path : /Approved
    Approved.service-id : Manager
    
    
management:
  security:
    enabled: false
    


