server:
  port: 9090

spring:
  datasource:
    url: ${cloud.services.ams-ui.connection.jdbcUrl:jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/ad_a3ef5be9a5a9791?user=bdebe42a825a2c&password=e9f2cac767354a5}
  application:
    name: employee

  data:
    mongodb:
      database: Attendance
      host: localhost
      port: 27017

  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQLDialect
    show-sql: true
    

zuul:
  routes:
    employee.path : /manager
    employee.service_id : Manager
    
    getApprovalList.path : /getApprovalList
    getApprovalList.service-id : Manager
    
    ams.path : /js/ams1.js
    ams.service-id : Manager
    
    getPendingList.path : /getPendingList
    getPendingList.service-id : Manager
    
    Approved.path : /Approved
    Approved.service-id : Manager
    
    
management:
  security:
    enabled: false

security:
  oauth2:
    client:
      clientId: 0oab1wn07kwBdEJt00h7
      clientSecret: IsEMnCIMN3-fRqb5VKwOo1eVFdYmP6J4Vx0lI_OR
      accessTokenUri: https://dev-255264.oktapreview.com/oauth2/ausb244zmpip4VuKf0h7/v1/token
      userAuthorizationUri: https://dev-255264.oktapreview.com/oauth2/ausb244zmpip4VuKf0h7/v1/authorize
      clientAuthenticationScheme: form
      scope: openid profile email
      
    resource:
      userInfoUri: https://dev-255264.oktapreview.com/oauth2/ausb244zmpip4VuKf0h7/v1/userinfo
      preferTokenInfo: false    
